# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The 
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Profile"
      responses:
        '200':
          description: User registration successful. Returns the ID of the user.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        '400':
          description: Bad Request. Validation failed. Error message contains failed fields and rules.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/RegisterErrorResponse"
        '409':
          description: Conflict Error. Phone Number Already Exists
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/RegisterErrorResponse"

components:
  schemas:
    Profile:
      type: object
      required:
        - phone_number
        - full_name
        - password
      properties:
        phone_number:
          type: string
          minLength: 10
          maxLength: 13
          pattern: '^\+62\d{9,12}$'
        full_name:
          type: string
          minLength: 3
          maxLength: 60
        password:
          type: string
          minLength: 6
          maxLength: 64
          pattern: '^(?=.*[A-Z])(?=.*\d)(?=.*\W).*$'
    RegisterResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        created_id:
          type: integer
    RegisterErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string